### ISSUE TITLE
Styling bugs

### ISSUE THREAD

**Issue by MarijaKnezevic** [tum-gis/ckan-docker#20]
The following issues are opened in their repositories:

- [x] [Main category Preview in Dataset view](https://github.com/tum-gis/ckanext-grouphierarchy-sddi/issues/4)
- [x] [On the Start Page of the catalog should be just Main Category visible](https://github.com/tum-gis/ckanext-grouphierarchy-sddi/issues/5)
- [x] [Remove „Add to group“ button](https://github.com/tum-gis/ckanext-grouphierarchy-sddi/issues/6)
- [x] #21
- [x] Spatial Attirbute when Dataset is Created - remove (+) symbol and show dataset extent with map when Dataset is created
- [x] remove "visibility" attribute and if the "Custom Field" is not defined, then don't show this as attribute when the dataset is created

When one of the bugs from the list is solved, it will be marked and the issue will be updated.
