### ISSUE TITLE
Drop `sddi-social` image

### ISSUE THREAD

**Issue by BWibo** [tum-gis/ckan-docker#66]
- Remove the `sddi-social` image, as it has never been completed, test nor being used.

### Todos

- [x] Remove Dockerfile folder
- [x] Remove any traces from docs, mainly in [README.md](README.md)
- [ ] Delete `sddi-social` images from:
  - [ ] Dockerhub
  - [ ] ghcr.io
- [x] Remove `sddi-social` parts from workflows

**Comment by BWibo** [comment]
@MarijaKnezevic Please check if all of the todos listed above are completed in #71.
