### ISSUE TITLE
Rework how to extend this image

### ISSUE THREAD

**Issue by BWibo** [tum-gis/ckan-docker#67]
We are moving away from the initial idea to add folders for images, that extend our base-image. Extension images should live in separate repos in the future. This repo will only maintain `sddi-base`, and `sddi` image flavor in the future. 
We want to provide a template folder with Github workflows and Dockerfiles, that can be used as a starting point for extending this image.

### Todos

- [ ] Rework docs to describe the new approach
- [ ] Provide template folder structure for extending this image
- [ ] Rework build workflows, to work out of the box wi´hen starting a fresh Github repo from the template folder

**Comment by gislab-augsburg** [comment]
Hi, can you give a time horizon when the templates for extending the base-image in seperate repos will be ready?

If it takes a while, we will maybe build a seperate repo for our 'sddi-urban' image on our own. Also we could contribute this or parts of it as a draft for your proposed templates.

Actually we are also thinking about moving away from using your base image in order to reduce dependencies. But what I really appreciate in your new base image version is:
- Upgrade to CKAN 2.11
- Reducing the extensions
- Using only stable, maintained extensions
- Removing the dependency from keitaroinc/ckan in favor of ckan/ckan-base

**Comment by BWibo** [comment]
Oh, tbh I completely forgot about this. We are currently focussing on getting the Helm charat `v4` on the road.
The template should not be too much work. Let's recap here what we disscussed back then. 

The template should contain:
- Template workflows, that will work out of the box or wirh little configuration in a different repo on Github
- Template Dockerfiles that work with the build workflows.
- A guide how to create a the fresh repo

Anything missing?

**Comment by gislab-augsburg** [comment]
Cool, nothing missing in your description. For us it would be fine if the template contains the structure just for a custom addon image and we continue to use it on top of your base image.
